[package]
name = "rust-control-panel-template"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
prisma-client-rust = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }
serde = "1.0"
serde_json = "1.0"
anyhow = "1.0"
log = "0.4"
tracing-subscriber = { version = "0.3", features = ["env-filter", "std"] }
poem = { version = "3.1.1" }
http = "1.1.0"
reqwest = "0.12.8"

[build-dependencies]
prisma-client-rust-cli = { git = "https://github.com/Brendonovich/prisma-client-rust", tag = "0.6.11" }

[[bin]]
name = "server"
path = "bin/server.rs"

[[bin]]
name = "prisma"
path = "bin/prisma.rs"
